import { Component, OnInit, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { OrganizerStore } from '../../state/organizer.store';

@Component({ selector: 'app-organizer-event-checkin', imports: [FormsModule, RouterLink], template: `
  <main class="organizer-page"><header class="page-header"><div><span class="eyebrow">Validação server-side</span><h1>Check-in</h1><p class="muted">A autorização definitiva é feita pelo backend de ingressos.</p></div><a class="button secondary" [routerLink]="['/organizer/management/events', eventId]">Voltar</a></header><p class="notice">A validação usa o endpoint real de acesso. O histórico abaixo existe apenas nesta sessão e não é persistido.</p><section class="card"><div class="field-grid"><label>Código QR/hash<input [(ngModel)]="code" aria-label="Código QR ou hash" /></label><label>Gate ID<input [(ngModel)]="gateId" aria-label="Gate ID" /></label></div><button class="primary" style="margin-top:16px" [disabled]="store.loading()" (click)="validate()">{{ store.loading() ? 'Validando...' : 'Validar acesso' }}</button>@if (store.error()) {<p class="notice">{{ store.error() }}</p>}</section><section class="card" style="margin-top:24px"><h2>Validações desta sessão</h2>@if (!store.validations().length) {<p class="muted">Nenhuma validação realizada nesta sessão.</p>} @else {<div class="table-wrap"><table><thead><tr><th>Código</th><th>Resultado</th><th>Mensagem</th><th>Ingresso</th></tr></thead><tbody>@for (item of store.validations(); track $index) {<tr><td>{{ item.code }}</td><td>{{ item.result ?? (item.isAllowed ? 'Permitido' : 'Negado') }}</td><td>{{ item.message ?? 'Indisponível' }}</td><td>{{ item.ticketId ?? 'Indisponível' }}</td></tr>}</tbody></table></div>}</section><a class="button secondary" style="margin-top:16px" routerLink="/scanner">Abrir scanner existente</a></main>
`, styleUrl: '../../organizer.scss', standalone: true })
export class OrganizerEventCheckin implements OnInit { private readonly route = inject(ActivatedRoute); protected readonly store = inject(OrganizerStore); protected readonly eventId = this.route.snapshot.paramMap.get('eventId') ?? ''; protected code = ''; protected gateId = ''; ngOnInit(): void { if (this.eventId) { this.store.loadLogs(this.eventId); } } protected validate(): void { this.store.validateAccess(this.code, this.gateId); } }
