import { DatePipe } from '@angular/common';
import { Component, OnInit, inject } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { OrganizerStore } from '../../state/organizer.store';

@Component({ selector: 'app-organizer-event-sales', imports: [RouterLink, DatePipe], template: `
  <main class="organizer-page"><header class="page-header"><div><span class="eyebrow">Pedidos por evento</span><h1>Vendas</h1><p class="muted">Dados consultados no endpoint real de pedidos por evento.</p></div><a class="button secondary" [routerLink]="['/organizer/management/events', eventId]">Voltar</a></header>@if (store.loading()) {<p class="card">Carregando vendas...</p>} @else if (store.error()) {<p class="notice">{{ store.error() }}</p>} @else if (store.ordersLoaded() && !store.hasOrders()) {<p class="card">Ainda não há vendas registradas para este evento.</p>} @else {<section class="grid"><article class="stat"><span class="muted">Pedidos confirmados</span><strong>{{ store.confirmedOrders() }}</strong></article><article class="stat"><span class="muted">Pedidos pendentes</span><strong>{{ store.pendingOrders() }}</strong></article><article class="stat"><span class="muted">Total de pedidos</span><strong>{{ store.orders().length }}</strong></article></section><section class="card" style="margin-top:24px"><div class="table-wrap"><table><thead><tr><th>Pedido</th><th>Status</th><th>Valor</th><th>Itens</th><th>Data</th><th>Setores</th></tr></thead><tbody>@for (order of store.orders(); track order.id) {<tr><td>{{ order.id }}</td><td>{{ order.status ?? 'Indisponível' }}</td><td>{{ order.totalAmount ?? 'Indisponível' }}</td><td>{{ order.itemsCount ?? 'Indisponível' }}</td><td>{{ order.createdAt ? (order.createdAt | date:'dd/MM/yyyy HH:mm') : 'Indisponível' }}</td><td>{{ order.sectorNames.length ? order.sectorNames.join(', ') : 'Indisponível' }}</td></tr>}</tbody></table></div></section>}</main>
`, styleUrl: '../../organizer.scss', standalone: true })
export class OrganizerEventSales implements OnInit { protected readonly route = inject(ActivatedRoute); protected readonly store = inject(OrganizerStore); protected readonly eventId = this.route.snapshot.paramMap.get('eventId') ?? ''; ngOnInit(): void { if (this.eventId) { this.store.loadOrders(this.eventId); } } }
